spring:
  profiles:
    active: @environment@
  boot:
    admin:
      client:
        enabled: true
        instance:
          prefer-ip: true
          name: @application.name@-@environment@
  kafka:
    consumer:
      group-id: message-center-group
      enable-auto-commit: true
      auto-offset-reset: earliest
      auto-commit-interval: 1000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 3

logging:
  file: @application.name@
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always