server:
  port: 12345

# 消息推送
msg:
  maxPoolSize: 10
  queueName: queue.appmsg

# 短信推送
sms:
  maxPoolSize: 10
  queueName: queue.sms

# ActiveMQ
spring:
  activemq:
    password: admin
    user: admin
    broker-url: tcp://localhost:61616
    in-memory: false

# 个推
getui:
  appId: 123456789
  appKey: 987654321
  masterSecret: qwertyuiop
  url: http://sdk.open.api.igexin.com/apiex.htm

# 极光推送
jpush:
  masterSecret: 166a8222bd4e7b6e661b97d8
  appKey: 1380babcd5c9fdca637dae3c

# 腾讯云短信
qcloudsms:
  signName: 1234567
  appId: 123456
  appKey: 123456

# 云片
yunpian:
  apiKey: 123456

# 阿里大鱼短信
aliyun:
  accessKeyId: 1234567
  accessKeySecret: 1234567
  signName: 1234567

